### ISSUE TITLE
.getUsername not working with psn and xbl profiles

### ISSUE THREAD

**Issue by EndBug** [danielwerg/r6api.js#24]
The `.getUsername` method only works with pc users, for `xbl` and `psn` just returns an empty array.

**Comment by danielwerg** [comment]
Not even sure if it's because ubi now using this endpoint `https://public-ubiservices.ubi.com/v2/profiles?userId={ID}` which is cross platform search (uplay, psn, xbl, steam, etc) or because I never really bother to test stuff for consoles.

I'm rewriting whole package using typescript atm so I will implement better way to search there, but meanwhile I'll try to fix it in current version in a day or few.

PR is welcome, all we need to do is update url to the one I mentioned above and filter result by platform, since I don't want to add cross platform search without option to disable it.

Note to self: Mention in docs what you need to use `userId` instead of  `id` unless platform is uplay.

**Comment by danielwerg** [comment]
Fixed https://github.com/danielwerg/r6api.js/commit/61c71041e010d3eba9484ea9d820d0decb398bba
