### ISSUE TITLE
Error while fetching stats

### ISSUE THREAD

**Issue by DevJeon1358** [danielwerg/r6api.js#26]
![image](https://user-images.githubusercontent.com/43531611/77134295-ae080580-6aa9-11ea-9ad6-5a6b3deaefa6.png)

**Comment by danielwerg** [comment]
ubi api is dead
see: `https://game-rainbow6.ubi.com/en-us/uplay/player-statistics/{ID}/multiplayer`

**Comment by thecharlee12** [comment]
I'm having the same issue

**Comment by EndBug** [comment]
Seems like they closed them during unscheduled maintenance in order to "mitigate the impact on their servers". They say there's no current ETA on when they'll put the APIs back online.
I saw that all the other stats website and so on stopped updating stats for the same reason, so I guess we'll just have to wait.

Source tweet from Ubi: https://twitter.com/Ubi_Fanch/status/1240984808748130304

**Comment by danielwerg** [comment]
seems like api is finally up

**Comment by DevJeon1358** [comment]
Checked via `https://game-rainbow6.ubi.com/` link.
API Route seems online, but need to check it is working with this package.

**Comment by EndBug** [comment]
I've quickly checked all the methods on RunKit and it seems working

**Comment by DevJeon1358** [comment]
@EndBug Good to hear, Seems this issue is solved, closing
